# top level stuff you probably don't need to touch
highlighter: rouge
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 4000
safe: true


# edit here to achieve your personal greatness
url: http://artnoage.github.io/
title: Vaios Laschos
author: Vaios Laschos
description: Personal blog and resume
avatar: profile.jpg
email: artnoage@gmail.com



# needed for travis-ci build
exclude: [vendor]
